[package]
name = "gtfs-realtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4"
prost = "0.11"

[build-dependencies]
prost-build = "0.11"